name: deploy staging
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'dockerfile'

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build image
        run: |
          docker build . -t evannurandiz00/testing:latest

      - name: push image to docker hub
        run: |
          docker login -u evannurandiz00 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push evannurandiz00/testing:latest
  
      - name: Create .env file on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cat > ~/docker-compose-app/.env << EOT
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_NAME=${{ secrets.DB_NAME }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            EOT

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/docker-compose-app
            sudo docker-compose -f docker-compose-app.yml pull
            sudo docker stack config -c docker-compose-app.yml
            sudo docker stack deploy -c docker-compose-app.yml app
            sudo rm -rf .env
